### 

# @name Get All Notes

GET http://localhost:5000/api/notes HTTP/1.1
Accept: application/json


### 

# @name Get Note by ID

GET http://localhost:5000/api/notes/69bfc1cbf72acf2ac21635d3 HTTP/1.1
Accept: application/json


### 

# @name Create Note

POST http://localhost:5000/api/notes HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "text": "This is line 1\nThis is line 2\n\n\nThis is line 5\nThis is line 6\nThis is line 7\n",
  "title": "Note with many lines"
}


### 

# @name Update Note by ID

PATCH http://localhost:5000/api/notes/69bfc084f72acf2ac21635d2 HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "text": "Check out my next app and now behold it is updated",
  "title": "My first note"
}


### 

# @name Delete Note by ID

DELETE http://localhost:5000/api/notes/69c7fb5a9524bbf79b8f92db HTTP/1.1
Accept: application/json
